services:
  ilias-downloader:
    restart: always
    env_file:
      - .env
    image: therealjohannes/kit-ilias-downloader
    volumes:
      # the default location of the rclone config (check with `rclone config file`)
      - $HOME/.config/rclone:/root/.config/rclone

## -- optional --

##    (1)  mount the path to local data folder to persist downloads
#     - ./data:/code/data

##    (2)  mount path to self-compiled ilias downloader executable
##    (for example for arm devices, as the provided one does not work here)
#      - $HOME/.cargo/bin/KIT-ILIAS-downloader:/code/data/kit-downloader/KIT-ILIAS-downloader